version: '2'
services:
  filebeat:
    build: filebeat
    volumes:
      - ./filebeat/rsvps.sample:/var/log/rsvps.log
      - ./filebeat/run.sh:/opt/filebeat/run.sh
    command: "/opt/filebeat/run.sh"
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
